### PR TITLE
Handle additional non-bitstypes unions

### LINKED ISSUE #43: Indefinite number of fields error with some Union types
Simplest reproducer (initially surfaced when passing some `NCASubject`s through Dagger) I can come up with:

```
julia> VERSION
v"1.5.3-pre.0"

(Sandbox) pkg> st MemPool
Project Sandbox v0.1.0
Status `~/code/julia/Sandbox/Project.toml`
  [f9f48841] MemPool v0.3.2

julia> using MemPool

julia> poolset(Union{Nothing,Vector{Float64}}[nothing])
ERROR: ArgumentError: type does not have a definite number of fields
Stacktrace:
 [1] fieldcount(::Any) at ./reflection.jl:703
 [2] fixedlength(::Type{T} where T, ::IdDict{Any,Any}) at /home/mike/.julia/packages/MemPool/F33TL/src/io.jl:158
 [3] fixedlength(::Type{T} where T) at /home/mike/.julia/packages/MemPool/F33TL/src/io.jl:148
 [4] approx_size(::Type{T} where T, ::Int64, ::Array{Union{Nothing, Array{Float64,1}},1}) at /home/mike/.julia/packages/MemPool/F33TL/src/MemPool.jl:79
 [5] approx_size(::Array{Union{Nothing, Array{Float64,1}},1}) at /home/mike/.julia/packages/MemPool/F33TL/src/MemPool.jl:75
 [6] poolset(::Any, ::Int64) at /home/mike/.julia/packages/MemPool/F33TL/src/datastore.jl:116 (repeats 2 times)
 [7] top-level scope at REPL[6]:1
```

Doesn't show up when it's a union of bitstypes like `Union{Nothing,Float64}`, so I'd guess it's got something to do with https://github.com/JuliaComputing/MemPool.jl/blob/a279024c8c6a3dba246b2303808f5fdd6bbe247a/src/io.jl#L150 perhaps?

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Fixes #43. I'm not too familiar with this code, so not 100% sure this is a suitable fix. Tests pass locally with this change, so maybe.

### CODE REVIEW

**Comment by shashi** [comment]
looks good! maybe a test will  keep it working?

**Comment by MichaelHatherly** [comment]
> maybe a test will keep it working?

Added a more direct test in addition to the `roundtrip` one.

**Comment by MichaelHatherly** [comment]
Anything else need done here @shashi? Windows failures unrelated.

**Comment by MichaelHatherly** [comment]
Bump?

**Comment by jpsamaroo** [comment]
Thanks!

**Comment by MichaelHatherly** [comment]
@jpsamaroo, any chance we could get a new patch release containing this fix?

**Comment by jpsamaroo** [comment]
I'd like to do that, but right now we're having issues with `DRef` refcounting being broken-ish. I'm trying to get #45 finished up (95% done) so that MemPool is robust. If I don't merge and register by the end of next week, please ping me again and I'll merge #45 as-is anyway.

**Comment by jpsamaroo** [comment]
Ok, MemPool 0.3.3 will be released in the next few minutes.

**Comment by MichaelHatherly** [comment]
Thanks @jpsamaroo.

**Pull request merged**
