### PR TITLE
Thread safety

### PR DESCRIPTION
**Pull request by shashi**
Lock `datastore` and `id_counter` usage.

Also has some 1.0 pkg config.

### CODE REVIEW

**Comment by shashi** [comment]
@tanmaykm merge?

**Comment by jpsamaroo** [comment]
Bump. Is there anything else required before merging this?

**Comment by tanmaykm** [comment]
LGTM. Added a commit just now to update appveyor.yml. Maybe just wait for the results?

**Comment by tanmaykm** [comment]
`unlink` is failing at many places on Windows. I suspect they are because of memory mapped files. Somehow they still in use?

**Comment by jpsamaroo** [comment]
Those tests have been failing since before this PR. I encountered them when I submitted my last (trivial and unrelated) PR too.

**Pull request merged**
