### PR TITLE
Add RemoteChannel based finalizer on DRef

### PR DESCRIPTION
**Pull request by nkottary**

### CODE REVIEW

**Comment by nkottary** [comment]
I looks like the finalizer for `r3 = poolset([Ref(1),Ref(2)], 2)` runs immediately after `@test poolget(r2) == ["abc","def"]` so `@test r3 = poolset([Ref(1),Ref(2)], 2)` fails.

https://github.com/JuliaComputing/MemPool.jl/blob/86cf0cafbd1b6db9358fc100af91d52bd39c92cc/test/runtests.jl#L106

@shashi Any idea why this happens?

**Comment by nkottary** [comment]
Okay, I see from the docs of `Ref` that unless there is a reference to the `Ref` itself, it is gc'd. Can we remove/change this test?

**Comment by nkottary** [comment]
Tests for Dagger also fail with this.

**Comment by shashi** [comment]
No it should have worked. I'm guessing this is some compiler optimization that kicks in that decides the remotechannel field is not worth keeping around (DRef is a stack object and is only defined in that testset block.)

**Comment by shashi** [comment]
Let me try a thing

**Comment by shashi** [comment]
can you reproduce this locally btw? I couldn't.

**Comment by shashi** [comment]
Oh okay, I think all my hypotheses so far are wrong :-p

```julia
julia> using Distributed

julia> @everywhere function test()
           r = RemoteChannel()
           finalizer(r) do r
               @async println("GC'd")
           end
           r
       end

julia> r = remotecall_fetch(test, 2)
RemoteChannel{Channel{Any}}(2, 2, 4)

julia> @everywhere GC.gc()
      From worker 2:	GC'd
```

So it seems `RemoteChannel` object just gets gc'd on the workers as any other object would, it announces this to everyone else who may have the channel. So what we need to do is not to set up a finalizer for the RemoteChannel, but instead to hook into the mechanism which eventually can see that no one has a reference to it... @amitmurthy will know immediately what to do here. I'll dig in for like 15 more minutes.

**Comment by shashi** [comment]
Okay I think the checks in my last commit to figure out when the RemoteChannel is not with anyone else are wrong. You're welcome to read Distributed stdlib and play with it, or else I'll take a look at this later.

**Comment by jpsamaroo** [comment]
Superseded by #40

**Pull request closed without merging**
